# Generated by Django 3.2.6 on 2021-08-21 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('return_id', models.BigIntegerField(unique=True)),
                ('operation_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.BigIntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_surname', models.CharField(max_length=100)),
                ('customer_PID', models.CharField(max_length=30, null=True)),
                ('customer_account', models.CharField(max_length=50)),
                ('sender_bank_code', models.BigIntegerField(blank=True, null=True)),
                ('sender_company_name', models.CharField(max_length=100)),
                ('sender_bank_account', models.CharField(max_length=29)),
                ('payment_details', models.TextField(verbose_name='payment details')),
                ('status', models.CharField(choices=[('NEW', 'New record'), ('OK', 'Proceed with payment'), ('CHECK', 'Manual check needed'), ('PAID', 'Return was paid'), ('REVIEW', 'Under review'), ('BLOCK', 'Blocked return')], default='NEW', max_length=6, verbose_name='status')),
                ('comments', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-operation_date'],
            },
        ),
    ]
