# Generated by Django 3.2.6 on 2022-03-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrecord',
            name='sender_bank_account',
        ),
        migrations.RemoveField(
            model_name='returnrecord',
            name='sender_bank_code',
        ),
        migrations.RemoveField(
            model_name='returnrecord',
            name='sender_company_name',
        ),
        migrations.AlterField(
            model_name='returnrecord',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OK', 'Proceed'), ('CHECK', 'Check'), ('PAID', 'Paid'), ('REVIEW', 'Review'), ('BLOCK', 'Block')], default='NEW', max_length=6, verbose_name='status'),
        ),
    ]
