# Generated by Django 3.2.6 on 2021-08-18 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnrecord',
            options={'ordering': ['-operation_date']},
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='brand',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='customer_PID',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='customer_account',
            field=models.CharField(default='UA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='customer_name',
            field=models.CharField(default='initial', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='customer_surname',
            field=models.CharField(default='initial', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='operation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='order_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='payment_details',
            field=models.TextField(default=1, verbose_name='payment details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='return_id',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='sender_bank_account',
            field=models.CharField(default='UA', max_length=29),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='sender_bank_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='sender_company_name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='status',
            field=models.CharField(choices=[('NEW', 'New record'), ('OK', 'Proceed with payment'), ('CHECK', 'Manual check needed'), ('PAID', 'Return was paid'), ('REVIEW', 'Under review'), ('BLOCK', 'Blocked return')], default='NEW', max_length=6, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
