# Generated by Django 3.2.6 on 2021-08-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='slug',
            new_name='brand_slug',
        ),
    ]
