# Generated by Django 3.2.6 on 2022-03-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_rename_slug_brand_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sender_bank_account',
            field=models.CharField(default='', max_length=29),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='sender_bank_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='sender_company_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
