# Generated by Django 3.2.6 on 2022-03-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_auto_20220321_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='sender_company_name',
        ),
    ]
