# Generated by Django 3.2.6 on 2022-03-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_remove_brand_sender_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_slug',
            new_name='slug',
        ),
    ]
