# Generated by Django 3.2.6 on 2022-03-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_rename_brand_slug_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
