# Generated by Django 3.2.6 on 2022-03-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_alter_brand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='code',
            field=models.IntegerField(),
        ),
    ]
